### ISSUE TITLE
pihole-updatelists

### ISSUE THREAD

**Issue by SolidRhino** [pluim003/docker-pihole-unbound#19]
I found a script to add ad list from remote sources. Can you please add this script.
[pihole-updatelists](https://github.com/jacklul/pihole-updatelists)

**Comment by pluim003** [comment]
I'll take a look. I already at pihole-cloudsync to sync your lists between different piholes and and addlist-tool to check if all lists are really required.

A bit later: doesn't it do the same as an updategravity? Which is being done once a week in the container. But it also does it when restarting if I'm not mistaken (and as I seem to notice).

**Comment by pluim003** [comment]
Actually this is not an issue. Would be better for a discussion. And I'm not willing to add this. The lists will be updated weekly and on a restart of the container. An option could be to use a modified cron-file for pihole that it will do an update daily. Maybe through a mapping or whatever.

**Comment by pluim003** [comment]
I'm closing this as I won't be adding this.
