### ISSUE TITLE
Pi-hole Update

### ISSUE THREAD

**Issue by pochacho99** [pluim003/docker-pihole-unbound#34]
Will you be updating your image to the new pi-hole version?

**Comment by pluim003** [comment]
I haven't been active for a while but around July there were some issues after updating, but I have an updated version with Pihole 2024.07.0 and Unbound 1.17.1 as things had changed and the regular way of updating/upgrading didn't work anymore. 

I finally got the nightly build working as well with Pihole 2024.07.0, but Unbound 1.21.1.

**Comment by pluim003** [comment]
Hi @pochacho99 the latest update contains now Pihole dockertag 2024.07.0 and Unbound 1.21.1. I don't know your setup but might need some small changes. Feel free to ask. For now I can't continue with the nightly release as pihole totally changed that image using Alpine Linux and I can't get it working to add unbound to it and neither have I tried the regular pihole-nightly-image yet.

**Comment by pochacho99** [comment]
Hi Dick, thanks for updating the image. I have it on watchtower, so it automatically pulled your latest October image and seems to be working fine.

 

Regards,

 

Philip

**Comment by pochacho99** [comment]
Hi Dick, I’ve just updated to your latest image and it seems to be working fine. Thanks again!

**Comment by pluim003** [comment]
Thanx for the feedback. I'll try to keep the image up-to-date again but I'm afraid no new 'old-style' pihole docker-images will be released so new updates will probably only consist of images with a new unbound-version. And if I have some more time I'll dig into the new pihole further.
